In [1]:
import numpy as np

## Datatypes & Attributes

In [5]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([[1, 2.0, 3.3],
                [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])


In [15]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [16]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [17]:
a1.shape

(3,)

In [18]:
a2.shape
a3.shape

(2, 3, 3)

In [19]:
a2.shape

(2, 3)

In [20]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)