In [1]:
import numpy as np

## Datatypes & Attributes

In [5]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([[1, 2.0, 3.3],
                [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])


In [15]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [16]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [17]:
a1.shape

(3,)

In [18]:
a2.shape
a3.shape

(2, 3, 3)

In [23]:
a2.shape

(2, 3)

In [24]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [25]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [21]:
## ndim is short for number of dimensions

In [22]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [26]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [27]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [28]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

 ## ndarray is a universial datatype

In [31]:
# create a DataFrom from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating NumPy Arrays

In [33]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [34]:
sample_array.dtype

dtype('int64')

In [35]:
ones = np.ones((2, 3))

In [36]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
ones.dtype

dtype('float64')

In [39]:
type(ones)

numpy.ndarray

In [42]:
zeros = np.zeros((2, 3))

In [43]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
range_array = np.arange(0, 12, 2)
range_array

array([ 0,  2,  4,  6,  8, 10])

In [54]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[1, 3, 8, 4, 6],
       [1, 0, 6, 6, 9],
       [2, 0, 5, 2, 6]])

In [55]:
random_array.size

15

In [56]:
random_array.shape

(3, 5)

In [61]:
random_array_2 = np.random.random((5, 3)) 
random_array_2

array([[0.13907556, 0.333225  , 0.22754341],
       [0.8470793 , 0.03235497, 0.01826067],
       [0.59103047, 0.04888156, 0.60340275],
       [0.59229779, 0.37576778, 0.7790664 ],
       [0.86701431, 0.88582309, 0.77160517]])

In [62]:
random_array_2.shape

(5, 3)

In [72]:
random_array_3 = np.random.rand(5, 3)

In [73]:
random_array_3

array([[0.88898183, 0.78324252, 0.38472975],
       [0.36276973, 0.18475646, 0.41685862],
       [0.56951113, 0.20669348, 0.35465351],
       [0.65476673, 0.69928022, 0.44322152],
       [0.57778378, 0.53023122, 0.32486935]])

## NumPY Random Seed

In [91]:
# Pseudeo-random arrays
np.random.seed(seed=9999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[6, 1, 6],
       [5, 5, 9],
       [6, 8, 0],
       [8, 1, 5],
       [3, 1, 0]])

In [76]:
random_array_4.shape

(5, 3)

In [92]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])